version: '1.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_APP_ENV=production
    restart: unless-stopped
